# Generated by Django 3.1.7 on 2023-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='ike_new',
            field=models.BooleanField(default=False),
        ),
    ]
