# Generated by Django 3.1.7 on 2023-02-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_ike_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='ike_new',
        ),
    ]
