# Generated by Django 3.1.7 on 2023-02-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_band_ike_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='hometown',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
